name: Job Monitor

on:
  schedule:
    - cron: '0 0,12 * * *'  # Run at midnight and noon UTC daily

  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-jobs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13.1'

    - name: Install Chrome and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Install dependencies
      run: |
        pip install -r src/requirements.txt

    - name: Check for job openings
      run: |
        cd src
        python job_crawler.py

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .github/data/
        git commit -m "Update job listings" || exit 0
        git push